### ISSUE TITLE
clone virtfuzz-qemu-videzzo failed

### ISSUE THREAD

**Issue by Chan9Yan9** [cyruscyliu/virtfuzz-evaluation#1]
Hello, I am currently trying to replicate your experiment. However, I encountered an issue while following the steps in your README when cloning qemu-videzzo. The error is as follows:
`fatal: Failed to recurse into submodule path 'roms/edk2'`
I also noticed that the _roms_ directory has been removed in the master branch. Should I directly clone the master branch to replicate the experiment, or are there any specific adjustments required?

**Comment by cyruscyliu** [comment]
Hey, thank you for reaching out.

Let me know which command failed. 

```
git clone -b v5.1.0-videzzo    --recurse-submodules \
    git@github.com:cyruscyliu/virtfuzz-qemu.git virtfuzz-qemu-videzzo    --depth=1
```
works on my side (you should use the HTTPs instead of SSH).

**Comment by Chan9Yan9** [comment]
Well, it seems like the issue was with my network connection. After configuring a proxy, the HTTPS method is working properly now. That's really awkward. Thank you for your response.
